[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
neo4rs = "0.7"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "1.0.69"
